# Generated by Django 6.0.1 on 2026-01-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblendinteraction',
            name='viewed',
        ),
        migrations.AddField(
            model_name='userblendinteraction',
            name='created_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userblendinteraction',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='userblendinteraction',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userblendinteraction',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
