# Generated by Django 6.0.1 on 2026-01-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userblendinteraction_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blends_rated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subtaste_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blends_created',
            field=models.IntegerField(default=0),
        ),
    ]
