# Generated by Django 6.0.1 on 2026-01-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_functionality', '0004_blend_average_rating_blend_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blend',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='blend',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='blend',
            name='is_saved',
        ),
        migrations.RemoveField(
            model_name='blend',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='blend',
            name='user',
        ),
    ]
